from enum import IntEnum

class AssetId(IntEnum):
    PLAYER = 0
    PLAYER_WITH_CAM = 1
    FOLLOWER_BOT = 2
    GROUND_TILE = 3
    GROUND_TILE_ROCKY = 4
    GROUND_TILE_STONES = 5
    GROUND_TILE_TREES = 6
    GROUND_TILE_TREES_2 = 7
    GROUND_TILE_FOREST = 8
    GROUND_TILE_HOUSE = 9
    GROUND_TILE_HOUSE_RED= 10
    GROUND_TILE_HOUSE_BLUE = 11
    GROUND_TILE_HOUSE_TRIPLE = 12
    GROUND_TILE_HOUSE_TRIPLE_RED = 13
    GROUND_TILE_HOUSE_TRIPLE_BLUE = 14
    GROUND_TILE_STREETLIGHT = 15
    GROUND_TILE_PATH = 16
    WATER_TILE = 17
    MOUNTAIN_TILE = 18
    RAMP_TO_MOUNTAIN = 19
    CARD_BASE_1 = 20
    CARD_BASE_2 = 21
    CARD_BASE_3 = 22
    EMPTY_TILE = 100 # Used for map gen, should never appear in network protocol.
