from enum import IntEnum

class AssetId(IntEnum):
    PLAYER = 0
    PLAYER_WITH_CAM = 1
    GROUND_TILE = 2
    GROUND_TILE_ROCKY = 3
    GROUND_TILE_STONES = 4
    GROUND_TILE_TREES = 5
    GROUND_TILE_TREES_2 = 6
    GROUND_TILE_FOREST = 7
    GROUND_TILE_HOUSE = 8
    GROUND_TILE_HOUSE_RED= 9
    GROUND_TILE_HOUSE_BLUE = 10
    GROUND_TILE_HOUSE_TRIPLE = 11
    GROUND_TILE_HOUSE_TRIPLE_RED = 12
    GROUND_TILE_HOUSE_TRIPLE_BLUE = 13
    GROUND_TILE_STREETLIGHT = 14
    GROUND_TILE_PATH = 15
    WATER_TILE = 16
    MOUNTAIN_TILE = 17
    RAMP_TO_MOUNTAIN = 18
    CARD_BASE_1 = 19
    CARD_BASE_2 = 20
    CARD_BASE_3 = 21
    EMPTY_TILE = 22 # Used for map gen, should never appear in network protocol.
