from enum import IntEnum

class AssetId(IntEnum):
    PLAYER = 0
    PLAYER_WITH_CAM = 1
    GROUND_TILE = 2
    GROUND_TILE_ROCKY = 3
    GROUND_TILE_STONES = 4
    GROUND_TILE_TREES = 5
    GROUND_TILE_TREES_2 = 6
    GROUND_TILE_FOREST = 7
    GROUND_TILE_HOUSE = 8
    GROUND_TILE_STREETLIGHT = 9
    MOUNTAIN_TILE = 10
    RAMP_TO_MOUNTAIN = 11
    CARD_BASE_1 = 12
    CARD_BASE_2 = 13
    CARD_BASE_3 = 14